apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: oracle-db
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1521
  selector:
    app: oracle-db
  clusterIP: None