apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        ports:
        - containerPort: {{ .Values.kafka.port }}
        env:
        - name: KAFKA_BROKER_ID
          value: "{{ .Values.kafka.brokerId }}"
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:{{ .Values.kafka.port }}
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.kafka.port }}
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        resources:
          requests:
            cpu: {{ .Values.kafka.cpu }}
            memory: {{ .Values.kafka.memory }}
          limits:
            cpu: {{ .Values.kafka.cpu }}
            memory: {{ .Values.kafka.memory }}
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka
      volumes:
      - name: kafka-data
        persistentVolumeClaim:
          claimName: kafka-data

