namespace: kafka
storageClassName: gp3-csi

kafka:
  image: quay.io/leonim/kafka
  port: 9092
  replicas: 1
  brokerId: 1
  storageSize: 5Gi
  cpu: "500m"
  memory: "3Gi"

topics:
  enabled: true
  configMapName: kafka-topics

