namespace: kafka
storageClassName: gp3-csi

kafka:
  image: quay.io/leonim/kafka
  port: 9092
  replicas: 1
  storageSize: 5Gi
  cpu: "500m"
  memory: "3Gi"
  failureThreshold: 15
  initialDelaySeconds: 1800
  periodSeconds: 1800
  timeoutSeconds: 10

topics:
  enabled: true
  configMapName: kafka-topics

