namespace: kafka
storageClassName: gp3-csi

kafka:
  image: apache/kafka:3.7.0
  port: 9092
  replicas: 1
  brokerId: 1
  storageSize: 5Gi
  cpu: "500m"
  memory: "3Gi"

topics:
  enabled: true
  configMapName: kafka-topics

