namespace: default
storageClassName: gp3-csi

image:
  repository: quay.io/leonim/testd
  tag: latest
  pullPolicy: IfNotPresent
 
replicaCount: 1

trapd:
  port: 162
  storageSize: 100M
  failureThreshold: 15
  initialDelaySeconds: 1800
  periodSeconds: 1800
  timeoutSeconds: 10

kafka:
  host: kafka
  namespace: kafka
  port: 9092
  fqdn: ""  # if empty, build kafka.<namespace>.svc.cluster.local:9092
 
resources:
  limits:
    cpu: "100m"
    memory: "128Mi"
  requests:
    cpu: "50m"
    memory: "64Mi"
 